### ISSUE TITLE
请问这是什么情况？

### ISSUE THREAD

**Issue by jeromehan** [Xheldon/NotionEditor#1]
![image](https://user-images.githubusercontent.com/19773879/71621153-b36f5580-2c08-11ea-8d68-c31677192230.png)

**Comment by Xheldon** [comment]
Sorry, this project is working in process, has a raw status now, not complete yet.

**Comment by Xheldon** [comment]
@jeromehan  Sorry, this project is working in process, has a raw status now, not complete yet.
